disqus: ## Your disqus_shortname, e.g. username
gitalk:
  enable: false ## If you want to use Gitment comment system please set the value to true.
  owner: ## Your GitHub ID, e.g. username
  repo: ## The repository to store your comments, make sure you're the repo's owner, e.g. gitalk.github.io
  client_id: ## GitHub client ID, e.g. 75752dafe7907a897619
  client_secret: ## GitHub client secret, e.g. ec2fb9054972c891289640354993b662f4cccc50
  admin: ## Github repo owner and collaborators, only these guys can initialize github issues.
uyan: ## Your uyan_id. e.g. 1234567
livere: ## Your livere data-uid, e.g. MTAyMC8zMDAxOC78NTgz
changyan: ## Your changyan appid, e.g. cyrALsXc8
changyan_conf: ## Your changyan conf, e.g. prod_d8a508c2825ab57eeb43e7c69bba0e8b
valine: ## https://valine.js.org
  enable: true
  appid: FH3ofq6ETMCzXCTpoMITLoyR-gzGzoHsz
  appkey: OCdDB4Amb3IkkwV55FCGr9KP
  notify: false
  verify: false
  placeholder: 快来评论吧~
  avatar: "mm" ## Gravatar type, see https://github.com/xCss/Valine/wiki/avatar-setting-for-valine
  pageSize: 15
  guest_info: nick,mail,link

google_search: false ## Use Google search, true/false.
baidu_search: false ## Use Baidu search, true/false.
swiftype: ## Your swiftype_key, e.g. m7b11ZrsT8Me7gzApciT
tinysou: ## Your tinysou_key, e.g. 4ac092ad8d749fdc6293
self_search: true ## Use a jQuery-based local search engine, true/false.
google_analytics: ## Your Google Analytics tracking id, e.g. UA-42425684-2
baidu_analytics: ## Your Baidu Analytics tracking id, e.g. 8006843039519956000
fancybox: true ## If you want to use fancybox please set the value to true.
show_category_count: false ## If you want to show the count of categories in the sidebar widget please set the value to true.
toc_number: false ## If you want to add list number to toc please set the value to true.
shareto: false ## If you want to use the share button please set the value to true, you must have hexo-helper-qrcode installed.
busuanzi: true ## If you want to use Busuanzi page views please set the value to true.
wordcount: false ## If you want to display the word counter and the reading time expected to spend of each post please set the value to true, and you must have hexo-wordcount installed.
widgets_on_small_screens: false ## Set to true to enable widgets on small screens.
canvas_nest:
  enable: false ## If you want to use dynamic background please set the value to true, you can also fill the following parameters to customize the dynamic effect, or just leave them blank to keep the default effect.
  color: ## RGB value of the color, e.g. "100,99,98"
  opacity: ## Transparency of lines, e.g. "0.7"
  zIndex: ## The z-index property of the background, e.g. "-1"
  count: ## Quantity of lines, e.g. "150"
donate:
  enable: false ## If you want to show the donate button after each post, please set the value to true and fill the following items according to your need. You can also enable donate button in a page by adding a "donate: true" item to the front-matter.
  github: ## GitHub URL, e.g. https://github.com/Kaiyuan/donate-page
  alipay_qr: ## Path of Alipay QRcode image, e.g. /img/AliPayQR.png
  wechat_qr: ## Path of Wechat QRcode image, e.g. /img/WeChatQR.png
  btc_qr: ## Path of Bitcoin QRcode image, e.g. /img/BTCQR.png
  btc_key: ## Bitcoin key, e.g. 1KuK5eK2BLsqpsFVXXSBG5wbSAwZVadt6L
  paypal_url: ## Paypal URL, e.g. https://paypal.me/tufu9441
post_copyright:
  enable: false ## If you want to display the copyright info after each post, please set the value to true and fill the following items on your need.
  author: ## Your author name, e.g. tufu9441
  copyright_text: ## Your copyright text, e.g. The author owns the copyright, please indicate the source reproduced.
love: false ## If you want the peach heart to appear when you click anywhere, set the value to true.
# plantuml: ## Using PlantUML to generate UML diagram, must install hexo-filter-plantuml (https://github.com/miao1007/hexo-filter-plantuml).
#     render: "PlantUMLServer" ##  Local or PlantUMLServer.
#     outputFormat: "svg" ## common options: svg/png
copycode: true ## If you want to enable one-click copy of the code blocks, set the value to true.
dark: false ## If you want to use the dark mode theme, set the value to true. Note: This feature is not complete, please open an issue if you have any problem.

menu:
  - page: Plus
    directory: https://ilx.info
    icon: fa-anchor
  - page: home
    directory: .
    icon: fa-home
  - page: archive
    directory: archives/
    icon: fa-archive
  - page: about
    directory: about/
    icon: fa-user
  - page: rss
    directory: atom.xml
    icon: fa-rss

widgets: ## Six widgets in sidebar provided: search, category, tag, recent_posts, recent_comments and links.
  - search
  - category
  - tag
  - recent_posts
  - recent_comments
  - links

links:
  - title: 屠城
    url: https://www.haomwei.com
  - title: XAOXUU
    url: https://xaoxuu.com
  - title: Charlie
    url: https://charlie-zzy.github.io
  - title: 欢迎交换友链
    url: http://www.ilx.info

timeline:
  - num: 1
    word: 2014/06/12-Start
  - num: 2
    word: 2014/11/29-XXX
  - num: 3
    word: 2015/02/18-DDD
  - num: 4
    word: More

badges:
  - lable: Powered by
    message: Hexo
    color: blue
    url: https://hexo.io
    # title: Hexo
  - lable: Theme
    message: Maupassant
    color: yellowgreen
    url: https://www.haomwei.com/technology/maupassant-hexo.html
  - lable: UV
    type: uv
    message: <i class="fa fa-spinner fa-spin fa-fw"></i>
    color: orange
  - lable: PV
    type: pv
    message: <i class="fa fa-spinner fa-spin fa-fw"></i>
    color: lightgray
  - logo: 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMzg5Ljg2IiBoZWlnaHQ9IjEzMi4wNSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4gIDxnPiAgPHRpdGxlPmJhY2tncm91bmQ8L3RpdGxlPiAgPHJlY3QgZmlsbD0ibm9uZSIgaWQ9ImNhbnZhc19iYWNrZ3JvdW5kIiBoZWlnaHQ9IjEzNC4wNSIgd2lkdGg9IjM5MS44NiIgeT0iLTEiIHg9Ii0xIi8+ICA8ZyBkaXNwbGF5PSJub25lIiBpZD0iY2FudmFzR3JpZCI+ICAgPHJlY3QgZmlsbD0idXJsKCNncmlkcGF0dGVybikiIHN0cm9rZS13aWR0aD0iMCIgeT0iMCIgeD0iMCIgaGVpZ2h0PSIxMDAlIiB3aWR0aD0iMTAwJSIgaWQ9InN2Z18xIi8+ICA8L2c+IDwvZz4gPGc+ICA8dGl0bGU+TGF5ZXIgMTwvdGl0bGU+ICA8ZyBzdHJva2U9Im51bGwiIGlkPSJzdmdfMTQiPiAgIDxnIHN0cm9rZT0ibnVsbCIgdHJhbnNmb3JtPSJtYXRyaXgoMC45OTg3NDc5NDgwMDA5MTkyLDAsMCwwLjk5ODc0Nzk0ODAwMDkxOTIsLTk3OTcuNDA2MTg0ODA2MDksLTY4MjIuMjUxMzQ1MDgyMzg2KSAiIGlkPSJzdmdfNSI+ICAgIDxwYXRoIHN0cm9rZT0ibnVsbCIgaWQ9InN2Z182IiBkPSJtOTkxNS4zNjcxMiw2ODQ0LjA3NjgzbDAsMGwwLDBsMCwwbDAsMGMtMi40NzMsLTEuODYxIC01LjAzNCwtMy41MiAtNy42NjQsLTQuOTgzYy0xLjkwNCwtMS4wNTkgLTQuMjk1LC0wLjU2NCAtNS42MDQsMS4xNzdsLTE2LjQ5MiwyMS45MTJsLTEuMTc2LDEuNTYzYy0xLjc4NiwyLjM3MyAtNC42MzgsMy42NjUgLTcuNjA1LDMuNTI5Yy0xLjA4MiwtMC4wNDkgLTIuMTY0LC0wLjAzOSAtMy4yNDIsMC4wMjljLTguMjg5LDAuNTI1IC0xNi4zMDgsNC41MjUgLTIxLjY5NCwxMS42ODFjLTQuMzMsNS43NTMgLTYuMjI5LDEyLjU3NiAtNS44NzksMTkuMjQ1YzAuMDYzLDEuMjAxIDAuNzU3LDIuMjk4IDEuODUxLDIuNzk2YzIuMjcsMS4wMzIgNC4wMTcsMy4xMzcgNC40NTQsNS44M2MwLjYxOCwzLjgwOSAtMS43MjIsNy41NTEgLTUuNDE4LDguNjU5Yy00LjM1NywxLjMwNiAtOC44MzIsLTEuMzYzIC05LjgxNCwtNS43MjRjLTAuNTMyLC0yLjM2MiAwLjA3OSwtNC43MTEgMS40NjMsLTYuNDhjMC43NjgsLTAuOTgxIDEuMTU0LC0yLjIwMyAxLjA0NCwtMy40NDRjLTAuNzU4LC04LjU1MiAxLjUyLC0xNy40MDIgNy4wOSwtMjQuODAyYzcuMDI2LC05LjMzNCAxNy43MTcsLTE0LjI3NCAyOC41NjIsLTE0LjMzN2MyLjA5LC0wLjAxMiA0LjA1MiwtMS4wMTEgNS4zMDksLTIuNjgxbDE1LjE4OCwtMjAuMTc4YzEuMTg5LC0xLjU3OSAwLjQyMSwtMy44NDggLTEuNDc2LC00LjQwNWMtMjUuNDMsLTcuNDYgLTUzLjkwNSwwLjkzNCAtNzAuOTYsMjMuMTQ2Yy0yMi4wOTksMjguNzgxIC0xNi43MjksNzAuMjc5IDExLjk4Nyw5Mi40NjJjMi42ODcsMi4wNzYgNS40ODIsMy45MDkgOC4zNiw1LjUwOGMxLjg5MywxLjA1MiA0LjI3NCwwLjUzNyA1LjU3NywtMS4xOTNsMTYuNDkyLC0yMS45MTFsMS4xNzYsLTEuNTYzYzEuNzg2LC0yLjM3MyA0LjYzOCwtMy42NjUgNy42MDUsLTMuNTI5YzEuMDgyLDAuMDQ5IDIuMTY0LDAuMDM5IDMuMjQyLC0wLjAyOWM4LjI4OSwtMC41MjUgMTYuMzA4LC00LjUyNSAyMS42OTQsLTExLjY4MWM0LjMzLC01Ljc1MyA2LjIyOSwtMTIuNTc2IDUuODc5LC0xOS4yNDVjLTAuMDYzLC0xLjIwMSAtMC43NTcsLTIuMjk4IC0xLjg1MSwtMi43OTZjLTIuMjcsLTEuMDMyIC00LjAxNywtMy4xMzcgLTQuNDU0LC01LjgzYy0wLjYxOCwtMy44MDkgMS43MjIsLTcuNTUxIDUuNDE4LC04LjY1OGM0LjM1NywtMS4zMDYgOC44MzIsMS4zNjMgOS44MTQsNS43MjRjMC41MzIsMi4zNjIgLTAuMDc5LDQuNzExIC0xLjQ2Myw2LjQ4Yy0wLjc2OCwwLjk4MSAtMS4xNTQsMi4yMDMgLTEuMDQ0LDMuNDQ0YzAuNzU4LDguNTUyIC0xLjUyLDE3LjQwMiAtNy4wOSwyNC44MDJjLTcuMDI2LDkuMzM0IC0xNy43MTcsMTQuMjc0IC0yOC41NjIsMTQuMzM3Yy0yLjA5LDAuMDEyIC00LjA1MiwxLjAxMSAtNS4zMDksMi42ODFsLTE1LjE4NywyMC4xNzdjLTEuMTgsMS41NjggLTAuNDM5LDMuODQyIDEuNDQ0LDQuMzk2YzI1LjYzMyw3LjUzNCA1NC4zNjgsLTEuMDQ1IDcxLjM4NCwtMjMuNjUyYzIxLjkyNiwtMjkuMTM1IDE2LjA4NSwtNzAuNTI5IC0xMy4wNDksLTkyLjQ1N3oiIGZpbGw9IiNGRkZGRkYiLz4gICAgPGcgc3Ryb2tlPSJudWxsIiBpZD0ic3ZnXzciPiAgICAgPHBhdGggc3Ryb2tlPSJudWxsIiBpZD0ic3ZnXzgiIGQ9Im0xMDAyNC4zNDExMiw2ODYyLjExMDgzbC0wLjAwMSwtMS41NjdjLTAuMDAxLC0xLjEzMyAtMC45MiwtMi4wNTIgLTIuMDUzLC0yLjA1MmwtNTEuNDI0LDBjLTEuMTM0LDAgLTIuMDUzLDAuOTE5IC0yLjA1MywyLjA1M2wwLDMuMTM3YzAsMS4xMzQgMC45MTksMi4wNTMgMi4wNTMsMi4wNTNsNDMuNjI5LDBjMS4yNTUsMCAyLjIyMSwxLjEwNyAyLjAzNCwyLjM0OGMtMS4yMjQsOC4xMTMgLTUuMDYxLDIzLjI4NSAtMTcuMDUxLDM3Ljg1NGMtMC44NDcsMS4wMjkgLTIuNDE5LDEuMDExIC0zLjI0MSwtMC4wMzljLTEwLjAzMiwtMTIuODI4IC0xMy4xMTksLTI1Ljk4IC0xMy45NjIsLTMwLjgyNmMtMC4xODQsLTEuMDYxIC0xLjE2NiwtMS43OTIgLTIuMjM3LC0xLjY3OGwtMS42NDMsMC4xNzRsLTEuNDQ5LDAuMTUxYy0xLjE4OCwwLjEyNCAtMi4wMjYsMS4yMjggLTEuODA4LDIuNDAzYzEuMDI4LDUuNTU4IDQuNzczLDIwLjg0MSAxNi41NDksMzUuMzg4YzAuNjgzLDAuODQzIDAuNjI1LDIuMDc2IC0wLjE3NSwyLjgxYy0xNC4zMzYsMTMuMTQ5IC0yNy4yMjksMTYuMDMxIC0zMS44NDEsMTYuNjU3Yy0xLjAyNywwLjE0IC0xLjc5NCwxLjAwOSAtMS43ODksMi4wNDZsMC4wMTUsMy4xNjljMC4wMDYsMS4yMiAxLjA2NSwyLjE3NCAyLjI3NiwyLjAzMmM1LjQ4NCwtMC42NDUgMjAuMTE2LC0zLjc0MyAzNi4yODQsLTE4LjYxM2MwLjc5OSwtMC43MzQgMi4wMTQsLTAuNzM0IDIuODEsMC4wMDNjNy44MTMsNy4yMzUgMTcuNzk5LDE0LjIxMSAzMS4yNjYsMTguNDk1YzEuMDkxLDAuMzQ3IDIuMjU5LC0wLjI4NyAyLjU4MiwtMS4zODVsMC44ODcsLTMuMDA3YzAuMzE4LC0xLjA3OCAtMC4yOTcsLTIuMTk4IC0xLjM2NywtMi41MzljLTEyLjI1MiwtMy45MDggLTIxLjI4NSwtMTAuMiAtMjguMzc4LC0xNi42NTFjLTAuODE4LC0wLjc0NCAtMC44NTksLTIuMDA2IC0wLjE0MSwtMi44NDZjMTkuOTg0LC0yMy4zOTYgMjAuMjMsLTQ4LjQzMiAyMC4yMjgsLTQ5LjU3eiIgZmlsbD0iI0ZGRkZGRiIvPiAgICAgPHBhdGggc3Ryb2tlPSJudWxsIiBpZD0ic3ZnXzkiIGQ9Im0xMDA2MC4wMzgxMiw2ODU1LjIwODgzbC0zLjEzNywwYy0xLjEzNCwwIC0yLjA1MywwLjkxOSAtMi4wNTMsMi4wNTNsMCwxMC45OTljMCwxLjEzNCAtMC45MTksMi4wNTMgLTIuMDUzLDIuMDUzbC03LjM3OSwwYy0xLjEzNCwwIC0yLjA1MywwLjkxOSAtMi4wNTMsMi4wNTNsMCwzLjEzN2MwLDEuMTM0IDAuOTE5LDIuMDUzIDIuMDUzLDIuMDUzbDcuMzc5LDBjMS4xMzQsMCAyLjA1MywwLjkxOSAyLjA1MywyLjA1M2wwLDE1LjkzM2MwLDEuMTM0IC0wLjkxOSwyLjA1MyAtMi4wNTMsMi4wNTNsLTcuMzc5LDBjLTEuMTM0LDAgLTIuMDUzLDAuOTE5IC0yLjA1MywyLjA1M2wwLDMuMTM3YzAsMS4xMzQgMC45MTksMi4wNTMgMi4wNTMsMi4wNTNsNy4zNzksMGMxLjEzNCwwIDIuMDUzLDAuOTE5IDIuMDUzLDIuMDUzbDAsMTUuMDY1YzAsMy4yNyAtMS4zMDcsOC42MDYgLTkuNjQ4LDkuMzFjLTEuMDc4LDAuMDkxIC0xLjkyMSwwLjk2NSAtMS45MjEsMi4wNDdsMCwzLjEyNWMwLDEuMTk2IDEuMDE3LDIuMTU3IDIuMjA5LDIuMDU1YzguMDk5LC0wLjY5MyAxNi42MDMsLTUuMjkyIDE2LjYwMywtMTYuNTM3bDAsLTE1LjA2NWMwLC0xLjEzNCAwLjkxOSwtMi4wNTMgMi4wNTMsLTIuMDUzbDYuNTU3LDBjMS4xMzQsMCAyLjA1MywtMC45MTkgMi4wNTMsLTIuMDUzbDAsLTMuMTM3YzAsLTEuMTM0IC0wLjkxOSwtMi4wNTMgLTIuMDUzLC0yLjA1M2wtNi41NTcsMGMtMS4xMzQsMCAtMi4wNTMsLTAuOTE5IC0yLjA1MywtMi4wNTNsMCwtMTUuOTMzYzAsLTEuMTM0IDAuOTE5LC0yLjA1MyAyLjA1MywtMi4wNTNsNi41NTcsMGMxLjEzNCwwIDIuMDUzLC0wLjkxOSAyLjA1MywtMi4wNTNsMCwtMy4xMzdjMCwtMS4xMzQgLTAuOTE5LC0yLjA1MyAtMi4wNTMsLTIuMDUzbC02LjU1NywwYy0xLjEzNCwwIC0yLjA1MywtMC45MTkgLTIuMDUzLC0yLjA1M2wwLC0xMC45OTljMCwtMS4xMzQgLTAuOTE5LC0yLjA1MyAtMi4wNTMsLTIuMDUzeiIgZmlsbD0iI0ZGRkZGRiIvPiAgICAgPHBhdGggc3Ryb2tlPSJudWxsIiBpZD0ic3ZnXzEwIiBkPSJtMTAwNzYuMzc2MTIsNjkzNS45NDU4M2MwLDEuMTM0IDAuOTE5LDIuMDUzIDIuMDUzLDIuMDUzbDIzLjEzOCwwYzEwLjIzOSwwIDE4LjU2OSwtNy45NCAxOC41NjksLTE3LjdsMCwtNDguNjNjMCwtMS4xMzQgLTAuOTE5LC0yLjA1MyAtMi4wNTMsLTIuMDUzbC0zOS42NTQsMGMtMS4xMzQsMCAtMi4wNTMsMC45MTkgLTIuMDUzLDIuMDUzbDAsNjQuMjc3em0yNS4xOTEsLTUuMTlsLTE1Ljg5NSwwYy0xLjEzNCwwIC0yLjA1MywtMC45MTkgLTIuMDUzLC0yLjA1M2wwLC0yMS44MWMwLC0xLjEzNCAwLjkxOSwtMi4wNTMgMi4wNTMsLTIuMDUzbDI1LjE2NywwYzEuMTM0LDAgMi4wNTMsMC45MTkgMi4wNTMsMi4wNTNsMCwxMy40MDZjMC4wMDEsNS43NjYgLTUuMDgsMTAuNDU3IC0xMS4zMjUsMTAuNDU3em0xMS4zMjYsLTUxLjg0M2wwLDE2LjYzMWMwLDEuMTM0IC0wLjkxOSwyLjA1MyAtMi4wNTMsMi4wNTNsLTI1LjE2NywwYy0xLjEzNCwwIC0yLjA1MywtMC45MTkgLTIuMDUzLC0yLjA1M2wwLC0xNi42MzFjMCwtMS4xMzQgMC45MTksLTIuMDUzIDIuMDUzLC0yLjA1M2wyNS4xNjcsMGMxLjEzNCwwIDIuMDUzLDAuOTE5IDIuMDUzLDIuMDUzeiIgZmlsbD0iI0ZGRkZGRiIvPiAgICAgPHBhdGggc3Ryb2tlPSJudWxsIiBpZD0ic3ZnXzExIiBkPSJtMTAxMDcuODk5MTIsNjg1NS4xNTQ4M2wtMjAuNDQsMGMtMS4xMzQsMCAtMi4wNTMsMC45MTkgLTIuMDUzLDIuMDUzbDAsMy4xMzdjMCwxLjEzNCAwLjkxOSwyLjA1MyAyLjA1MywyLjA1M2wyMC40NCwwYzEuMTM0LDAgMi4wNTMsLTAuOTE5IDIuMDUzLC0yLjA1M2wwLC0zLjEzN2MwLC0xLjEzNCAtMC45MTksLTIuMDUzIC0yLjA1MywtMi4wNTN6IiBmaWxsPSIjRkZGRkZGIi8+ICAgICA8cGF0aCBzdHJva2U9Im51bGwiIGlkPSJzdmdfMTIiIGQ9Im0xMDE4Ni4wMzExMiw2ODU4LjM0MDgzbC00Mi41NzMsMGMtMS4xMzQsMCAtMi4wNTMsMC45MTkgLTIuMDUzLDIuMDUzbDAsMy4xMzdjMCwxLjEzNCAwLjkxOSwyLjA1MyAyLjA1MywyLjA1M2w0Mi41NzMsMGMxLjEzNCwwIDIuMDUzLC0wLjkxOSAyLjA1MywtMi4wNTNsMCwtMy4xMzdjMCwtMS4xMzQgLTAuOTE5LC0yLjA1MyAtMi4wNTMsLTIuMDUzeiIgZmlsbD0iI0ZGRkZGRiIvPiAgICAgPHBhdGggc3Ryb2tlPSJudWxsIiBpZD0ic3ZnXzEzIiBkPSJtMTAxNjcuODM4MTIsNjg5NC42NTM4M2wyOS42NTcsMGMxLjEzNCwwIDIuMDUzLC0wLjkxOSAyLjA1MywtMi4wNTNsMCwtMy4xMzdjMCwtMS4xMzQgLTAuOTE5LC0yLjA1MyAtMi4wNTMsLTIuMDUzbC02NS41MSwwYy0xLjEzNCwwIC0yLjA1MywwLjkxOSAtMi4wNTMsMi4wNTNsMCwzLjEzN2MwLDEuMTM0IDAuOTE5LDIuMDUzIDIuMDUzLDIuMDUzbDIwLjI3NCwwYzEuNjM4LDAgMi42MTcsMS44MjQgMS43MTEsMy4xODlsLTEzLjQ5MiwyNC4zNDNjLTAuMzYzLDAuNTQ1IC0wLjYzMiwxLjA4IC0wLjgyMSwxLjYzM2MtMS4xMjksMy4yOTkgLTAuNjAxLDYuODM4IDEuNDUxLDkuNzFjMi4xNSwzLjAxIDUuNzA2LDQuODA2IDkuNTA5LDQuODA2bDM2Ljk3NiwwYzEuNjYyLDAgMy4xODEsLTAuODI5IDQuMDYxLC0yLjIxOGMwLjg2MywtMS4zNTkgMC45NjksLTMuMDM5IDAuMjgzLC00LjQ5NWwtOC41ODYsLTE2LjY0M2MtMC41MiwtMS4wMDggLTEuNzU5LC0xLjQwMyAtMi43NjYsLTAuODgzbC0yLjc4OCwxLjQzOWMtMS4wMDgsMC41MiAtMS40MDMsMS43NTggLTAuODgzLDIuNzY2bDUuMDU1LDkuNzk2YzAuNzA1LDEuMzY3IC0wLjI4NywyLjk5NSAtMS44MjUsMi45OTVsLTI5LjUyOCwwYy0xLjQ5MiwwIC0yLjgxLC0wLjY0NyAtMy42MTYsLTEuNzc1Yy0wLjM2NywtMC41MTIgLTAuODk5LC0xLjUzIC0wLjU4OSwtMi43OThjMC4wNTIsLTAuMjEyIDAuMTU3LC0wLjQxMyAwLjI3OCwtMC41OTZsMTYuMzk3LC0yOC43MmMxLjA1OCwtMS41OTIgMi44NDEsLTIuNTQ5IDQuNzUyLC0yLjU0OXoiIGZpbGw9IiNGRkZGRkYiLz4gICAgPC9nPiAgIDwvZz4gIDwvZz4gPC9nPjwvc3ZnPg=='
    lable: CDN # <img src="data:image/svg+xml;base64,PHN2ZyB3...C9nPgogIDwvZz4KIDwvZz4KPC9zdmc+"/>PV
    color: blue # one of brightgreen, orange, yellow, blueviolet, pink, red, blue, grey/gray, lightgrey/lightgray
    url: https://www.upyun.com/?utm_source=lianmeng&utm_medium=referral
    title: # for url

# Static files
js: js
css: css

# Theme version
version: 0.0.0
